Auto: Merge master upstream to fork (#1)
* junit-jupiter-engine in dependencies

To avoid this exception when running from Eclipse (note that this way of
declaring dependency is also shown in the official JUnit 5 examples,
https://github.com/junit-team/junit5-samples/blob/r5.0.3/junit5-vanilla-maven/pom.xml)

java.lang.NoClassDefFoundError:
org/junit/platform/engine/EngineDiscoveryRequest
	at org.junit.platform.launcher.core.LauncherFactory.create(LauncherFactory.java:59)
	at org.eclipse.jdt.internal.junit5.runner.JUnit5TestLoader.<init>(JUnit5TestLoader.java:31)
	at sun.reflect.NativeConstructorAccessorImpl.newInstance0(Native
Method)
	at sun.reflect.NativeConstructorAccessorImpl.newInstance(NativeConstructorAccessorImpl.java:62)
	at sun.reflect.DelegatingConstructorAccessorImpl.newInstance(DelegatingConstructorAccessorImpl.java:45)
	at java.lang.reflect.Constructor.newInstance(Constructor.java:423)
	at java.lang.Class.newInstance(Class.java:442)
	at org.eclipse.jdt.internal.junit.runner.RemoteTestRunner.createRawTestLoader(RemoteTestRunner.java:367)
	at org.eclipse.jdt.internal.junit.runner.RemoteTestRunner.createLoader(RemoteTestRunner.java:362)
	at org.eclipse.jdt.internal.junit.runner.RemoteTestRunner.defaultInit(RemoteTestRunner.java:306)
	at org.eclipse.jdt.internal.junit.runner.RemoteTestRunner.init(RemoteTestRunner.java:221)
	at org.eclipse.jdt.internal.junit.runner.RemoteTestRunner.main(RemoteTestRunner.java:205)
Caused by: java.lang.ClassNotFoundException:
org.junit.platform.engine.EngineDiscoveryRequest
	at java.net.URLClassLoader.findClass(URLClassLoader.java:381)
	at java.lang.ClassLoader.loadClass(ClassLoader.java:424)
	at sun.misc.Launcher$AppClassLoader.loadClass(Launcher.java:335)
	at java.lang.ClassLoader.loadClass(ClassLoader.java:357)
	... 12 more

* Update Maven configuration in all projects

* Disable Cucumber test (issue #6)

* Update copyright in README

* Remove test scope in several dependencies

* Add Maven multimodule configuration

* Disable failing tests (to be executed in Travis with confidence)

* Add Travis CI configuration file

* Update badges in README

* Install Google Chrome using apt-get in Travis

* Fix Gradle configuration in several projects

* Add Gradle multimodule configuration

* Add gradle test command in Travis script

* Update README links

* Unify style of pom.xml in legacy projects (JUnit 3, 4)

* Set version 5.1 also in Gradle configuration

* Update Maven config to junit-jupiter 5.2.0 and surefire-plugin 2.22.0

* Include groupId for maven-surefire-plugin (although it is the default one)

* Use Allure plugin in Gradle configuration

* Update mini doc for junit5-allure project

* Remove non necessary dependency in Gradle config

* Update junit-platform-engine to 1.2.0

* Fix gradlew command invocation

* Include gradle-wrapper binary

* Update Gradle configuration for JUnit 5.2.0

* Fix junit5-allure configuration

* Check Gradle version in Travix

* Update Gradle in Travis

* Revert "Update Gradle in Travis"

This reverts commit 046b62510a352a62f06ab5eadd94d8d47511a9ba.

* Set oraclejdk8 as jdk version in Travis config

* Update Gradle again in Travis configuration

* Add ppa for Gradle automatically in Travix

* Fix apt-get install command for Gradle

* Use different jobs for Maven and Gradle in Travis

* Include wrapper for Gradle

* Execute Gradle job using wrapper

* Set execution flag to Gradle wrapper

* Update spring-boot to 2.0.3.RELEASE

* Separate with a carriage return compile and test dependencies

* Use mockito-junit-jupiter for MockitoExtension

* Set trusty as distribution on Travis

* Update README with JUnit 5 versions and rate my cat app info

* Include testLogging in Gradle config

* Disable echo service (echo.jsontest.com) test due to flakiness

* Update to junit-jupiter 5.3.0-M1 and junit-platform 1.3.0-M1

* Update android-junit5 to 1.0.32

* Update junit5-android Gradle configuration

* Include new project using maven-failsafe-plugin and IT test

* Run junit5-failsafe project on Travis

* Use @RegisterExtension
in junit5-extension-model project

* Downgrade to surefire 2.21.0 for filtering by tags

* Remove static when using @RegisterExtension

* Revert "Remove static when using @RegisterExtension"

This reverts commit b7f7cf7efe5f941f2702181a603147b00c5a7337.

* Include example project for registering automatically extensions

* Remove non-necessary dependency

* Include test using JUnit 5's @DisabledOnOs

* Update maven-surefire-plugin version to 2.22.0 in filtering project

* Unify name of junit-platform.version property in tagging project

* Fix junit5-console-launcher Maven configuration

* Update to junit-jupiter 5.3.2 and junit-platform 1.3.2

* Include logback configuration file

* Bump selenium-jupiter to version 3.2.1

* Update links in README

* Update badges (Twitter and StackOverflow)